version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: woo-wordpress
    depends_on:
      - db
    ports:
      - "8085:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: woocommerce
      WORDPRESS_DB_USER: woouser
      WORDPRESS_DB_PASSWORD: woopassword
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: woo-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: woocommerce
      MYSQL_USER: woouser
      MYSQL_PASSWORD: woopassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: woo-phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  wordpress_data:
  db_data:
