version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'yourpassword'
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    restart: unless-stopped

